### ISSUE TITLE
Gcode messages only echo back the first

### ISSUE THREAD

**Issue by dougle** [synthetos/TinyG#103]
In Edge 438.02  on a V8 board, sending:
(msg_connecting)
(msg_connect)
(msg_connected)

Responds with:
_connecting
_connecting
_connecting

**Comment by aldenhart** [comment]
It turns out this is normal Gcode behavior. Gcode comments will echo the text of the comment is the first 3 letters of the comment are "msg" (case insensitive). This is to allow the signaling the "operator" on the "console"
