### ISSUE TITLE
One too few status reports

### ISSUE THREAD

**Issue by dougle** [synthetos/TinyG#109]
Sometimes when running a long command, i imagine that the cycle finishes between status reports leaving me with the last report:
{"sr":{"posx":39.824,"posy":39.824,"vel":2.56,"stat":6}}
     (incorrect position and velocity at rest)

Which is no good for control software trying to report back final position and velocity.
There needs to be one status report after the cycle ends.

V8  FB 438.02

**Comment by aldenhart** [comment]
@dougle - Is this still an open issue?

**Comment by dougle** [comment]
Yes i believe so, i will try to find some commands and setting to reproduce
this though as i can see it being tricky to triage.

**Comment by aldenhart** [comment]
Any progress on this? It may also be a good idea to try out edge 440.13 (or later) and see if this condition still exists. Thanks.
