### ISSUE TITLE
Please explain g61, G61.1 and G64. G02 and G03 Arcs form straight lines!

### ISSUE THREAD

**Issue by lasertechpros** [synthetos/TinyG#115]
I'm having trouble getting my TInyG and Shapeoko combo to perform Arcs. It simply creates an angle between the two points. I triple check my coordinates (I'm hand coding) and I's and J's. Also tried R and that didn't work either. I think it has something to do with the path mode or something.. but I'm not able to do arcs or circles....PLEASE HELP! 
Thank you!
Evan

**Comment by aldenhart** [comment]
Arcs are hard to generate by hand, and are usually just output by CAM programs. That said, you can test arcs with the following hand coded Gcode.


g0 x0 y0 z0 (position to zero)
g17 (select XY plane)
g2 x100 y100 i50 j50 f500 (draw a 180 degree arc)
