### ISSUE TITLE
Limit Switch state

### ISSUE THREAD

**Issue by cmcgrath5035** [synthetos/TinyG#122]
Item #73 asked this question that was never really answered - is there a status query that will dump the current state of switches?

Trying to help someone debug :https://www.synthetos.com/topics/problem-with-x-axis-limit-switches/#post-7297

**Comment by aldenhart** [comment]
There is currently no status query for switch state. This is an experimental item that is on the list to include.

**Comment by asantanna-applied** [comment]
I would like this feature.  In my particular use case, I would like to know if the limit switch is triggered before I attempt something.  It's a special purpose device in which this actually makes sense.
