### ISSUE TITLE
Homed Status?

### ISSUE THREAD

**Issue by cmcgrath5035** [synthetos/TinyG#134]
(this is intended as a Question)
I am perusing https://github.com/synthetos/TinyG/wiki/Status-Reports#status-report-contents.
Is there a method to determine if tinyG is in a "homed" state?
Something like stat = x.. (x=?)
From referenced table, stat=9 says machine is homing. 
Is it possible to determine, after a few operations following successful Homing cycle, if the machine still is 'homed'?
Said another way, it is safe to assume that the machine is 'homed'  immediately after the successful homing cycle. It is not so obvious what subsequent commands or operations might change that state back to not-homed, or if the homing cycle failed.

I am thinking it might be useful for the Chilipeppr TinyG widget to display a "Homed Y/N " field when folks start using alternate coordinate systems.

**Comment by aldenhart** [comment]
You can check the {hom:n} variables
It returns true/false (1/0) for homX ... homC and home is the entire machine
