### ISSUE TITLE
Incorrect value of pi?

### ISSUE THREAD

**Issue by lutorm** [synthetos/TinyG#147]
I just noticed that the settings file defines things like this:

#define A_RADIUS                    (M1_TRAVEL_PER_REV/(2*3.14159628))

I assume the value starting with 3.14 should be pi, but as far as I know, the value of pi is 3.14159265... The last 3 digits appear to be incorrect. Is there some reason for this?

**Comment by lutorm** [comment]
It seems it would be better to just use the macro M_PI, defined in util.h as 3.14159265358979323846264338327950288 instead of hardcoding it in all the settings anyway.

**Comment by aldenhart** [comment]
It's been substituted with M_PI. Look for an edge push with the change, soon.
