### ISSUE TITLE
Handling of an E Stop situation

### ISSUE THREAD

**Issue by rickcaddell** [synthetos/TinyG#149]
There is a lot of confusion about E Stop judging by the things I have read on this site and other CNC sites, especially by people with little experience. I would like to weigh in with my opinion backed by 45 years of machine tool hardware and software design. The CSA definition of Emergancy Stop is - "A function that is intended to avert harm or to reduce hazards to persons, machinery, or work in progress."

This does not always mean stopping motion an all types machines. I have worked on some machines like inertial welders where this is a bad idea. It is far safer to finish the welding operation. On CNC routers it is a good idea. However I believe that as far as the TinyG is concerned it should not loose control, or require a reset. 

In my opinion the TinyG should do a controlled stop like a feed hold but definately not loose position.The estop condition should be cleared with the alarm reset message.I know that it seems right to kill the drive chips in the software, but I do not agree with that. Wether or not a reset is required should be left up to the operator. However there needs to be more protection than the TinyG can provide by itself.

For one thing any controller could get in a loop that would ignore things like limit switches because of a software of hardware problem. The better way is to have an external E_Stop button that kills the power to the drives.This cannot be done with the TinyG because there is only one power connection. I would like to suggest that there should be two. One to power the microprocessor and one to power the stepper driver chips, the spindle and coolant outputs. Hitting an E Stop button that removes power to the drives without powering down the TinyG would be the way to go in my opinion. 

I have two machines, one with one motor per axis and one with two motors for X and Y.
I am currently using the A axis Max limit switch as an input from an E Stop button. It works, but then I have to reset the TinyG, and all bets are off as far as position and machine state are concerned. I often hit the E Stop because the part program is not operationg as I think it should, or I want to check something, not because there is anything dangerous going on. As it stands now I have to re-home the machine. Which on the machine with dual motors on X and Y is quite cumbersom. I have two gantry type axis with two motors on each axis and the TinyG does not handle dual motors on an axis, as far as homing is concerned.

I have to do a homing sequence, disable the drives, crank the axes up to hard stops, so the axis is square, then zero the position. I have to do this on both X and Y. On high precision jobs, I then use a spindle probe to check the square and find a feature on the fixture. Quite a long process. If the A axis Max limit switch caused a soft E stop or could be programed to do a feed hold, this would be better. It should not however turn off the spindle or coolant. That could be done by the software driving the TinyG where it could then be selectable depending on the part being worked on.

With a feed hold input and two power inputs to the TinyG I would have a much safer machine. I could have a feed hold button that stops motion, my software could decide wether to stop the spindle or not and a hard E Stop button that removes power from the driver chips on the TinyG.

The way things are the machine is more dangerous because I am hesitant to hit the E Stop button because of the recovery effort.

**Comment by giseburt** [comment]
Hi @rickcaddell ,

I agree with you with one exception: The "emergency" part of "E-Stop" implies that even when the software is out to lunch, the machine will somehow still stop "being dangerous."

That's clearly not an easy thing to accomplish, and different devices (CNC, laser cutters, 3D printers, etc) have different ways of making the device "not dangerous." All we can do is a reasonable best-effort.

In the G2 software and accompanying hardware (that we haven't yet released for general sales), we have solved this in a few different ways.

1) We have different traces for power to the drives and to the rest of the board. This allows one to cut driver power without losing software control. Of course, on a machine where disabling the driver means it drops the equivalent of a small car from 10 feet, that wouldn't be a good thing.

2) We have buffers between the MCU and the drivers, allowing the step/dir signals to be interrupted.

3) We have a 555 timer that, if the software doesn't interrupt it, will kill the power after a switch is thrown. This gives the software some time to "handle" the signal, but if it's out-to-lunch or too slow, the 555 timer will kill the signals. (I don't recall exactly what signals are interrupted. It may be enable as well as step/dir. That's a question that @aldenhart would have to answer, and he's on holiday vacation at the moment.)

Now, much of that is hardware, and it works with our new G2 firmware that supports these new features. G2 runs on an easily-obtained Arduino Due, so it's much easier to roll your own hardware. We will also be releasing our own hardware as well.

-Rob
