### ISSUE TITLE
return the MPO after a MOV is complete

### ISSUE THREAD

**Issue by anthonywebb** [synthetos/TinyG#151]
I am using the JSON serial api and I would like to get the MPO postition AFTER a mov is complete.  Is there a callback letting me know a mov has completed, or a way to tell the MPO command to wait until a mov currently in progress is complete before returning the MPO?

**Comment by aldenhart** [comment]
Add status ('stat') into the status report and look for the move STOP (stat=3), or END (stat=4)

**Comment by anthonywebb** [comment]
Perfect, that works like a charm @aldenhart thanks!
