### ISSUE TITLE
Limit switch hit causes TinyG to lock up.

### ISSUE THREAD

**Issue by rickcaddell** [synthetos/TinyG#162]
Firmware Edge 446.19

When a limit switch is hit, the TinyG sends out about 50 error messages, but does not flash the
spindle direction LED like in previous versions. After that the TinyG does not respond to messages,
including a reset, it has to be reset with the button or powered down. 

I tested 440.19 and when a limit switch is hit it sends out two

Old Man

**Comment by aldenhart** [comment]
I guess this edge is more experimental than most. Sigh. Thanks for pointing it out.

**Comment by aldenhart** [comment]
Update - working on this. Expect to push results soon.
