### ISSUE TITLE
problem with tinyg card

### ISSUE THREAD

**Issue by hernandd44** [synthetos/TinyG#165]
can not get chilipeppr running have a red light flashing on the tinyg light spdir on the tinyg keeps flashing.  not sure why.  is there a way i can reset the tinyg 
any suggestions.

**Comment by cmcgrath5035** [comment]
The reset button on tinyG will restart the FW.
Do you have limit switches connected to tinyG?
If so, they may not be properly configured. Disconnect them and try to reset again.
Flashing spdir is either 'bootloader running' or limit hit - shut down"
https://www.synthetos.com/forums/tinyg/tinyg-support/ might be a better place to chase this

**Comment by aldenhart** [comment]
I will close this and let the issue get handled on the forum.
