### ISSUE TITLE
Is system.c a dead file?

### ISSUE THREAD

**Issue by bdurbrow** [synthetos/TinyG#169]
In trying to fix the makefile to run with CrossPack on OS X; I noticed that system.c is not being compiled by the makefile; and attempting to add it to the makefile causes compilation to fail (the hardware version macro fails to expand). However, omitting it does not cause any link errors, so…

Is that a dead file?

**Comment by aldenhart** [comment]
Yes, it is a dead file. It has been removed from the edge branches and will be removed from master in the next push. Thanks
