### ISSUE TITLE
Home command random behavior 

### ISSUE THREAD

**Issue by nikky111** [synthetos/TinyG#172]
Hi,

Using the G28.2 homing command, whenever i homed any 
axis ,it sets y value to -ve of value(ytm) and its gets double after very homimg and sometimes to some random value.

I have upgraded its firmware(440.20) today and found this problem immediately.Is there bug in this firmware

I am using coolterm to send gcode file.Window 8 is system
Kindly let me know is there any solution to solve it asap.. Thank you in advance.

**Comment by ril3y** [comment]
Old issue closing.
