### ISSUE TITLE
G04 

### ISSUE THREAD

**Issue by cmcgrath5035** [synthetos/TinyG#173]
There is either a bug or documentation error/omission with regards to Gcode command G04
See Forum item https://www.synthetos.com/topics/gcode-g04-p0-hangs-job/#post-9594

A value of G04 P0 causes tinyG to hang.

A quick look at random Gcode documentation does not specifically discuss a zero duration pause.

If in fact this is intentional, perhaps documentation should state that duration MUST be >0.

**Comment by ril3y** [comment]
This seems to work in the current master branch just fine.
