### ISSUE TITLE
3rd axis parameter in g02 not implemented?

### ISSUE THREAD

**Issue by mikest** [synthetos/TinyG#19]
It appears as if the notably rare 3rd axis parameter in the g02 command is not implemented? Is useful for blade tangent control when cutting a circle on a knife cutter.

Probably for nothing else.

**Comment by jackjameshoward** [comment]
@aldenhart Is there any way to get the 3rd axis to work as a no linear axis, i.e. as a rotary axis? For the same reason as mikest intended, to use as an axis which runs tangent to the arc.
