### ISSUE TITLE
Control Via J17-20 Pins 

### ISSUE THREAD

**Issue by cago6586** [synthetos/TinyG#192]
Hello,

This isn't necessarily an issue, but more of a general question. (If there is somewhere better I can ask questions please let me know.)

I am wondering if I can use the enable/direction/step pins on J17-20 to directly control the stepper motors connected. For example, if I connect a motor, give power to the tinyg, and set up a function generator to put a square wave with some duty cycle into the step pin, would this cause the motor to rotate? 

Any help on this would be much appreciated! 

Thanks,
Carmelo

**Comment by aldenhart** [comment]
Yes, those pins are designed for just that. Please note that they are 3.3v outputs direct from the processor, and may need to be buffere to level shifted to 5v if the external driver requires it.
