### ISSUE TITLE
SuperPIDv2 Compatibliity

### ISSUE THREAD

**Issue by ejluttmann** [synthetos/TinyG#194]
The SuperPid v2 requires an active low on the spindel pin instead of an active high. I forked the TinyG project and added a configuration option back in Dec 2014 ($sal) to allow switching between active high and active low on the spindel pin. I entered an issue back in Dec 2014 (https://github.com/synthetos/TinyG/issues/116) and it was mentioned the functionality would be added.  

I noticed the issue was closed, so just wondering if his functionality was added to the code?  I'd like to upgrade to the latest firmware, but I need this functionality for the SuperPid v2 and I cannot seem to find reference to it in the documentation or the code.

You can find the original changes I made to make this work at https://github.com/ejluttmann/TinyG/commit/6469260c2338d080c923fd623808e542a38e7189.

Thanks,
Eric Luttmann

**Comment by ril3y** [comment]
Please provide a pull request.
