### ISSUE TITLE
[Hardware] ESD Update

### ISSUE THREAD

**Issue by mattpatt59** [synthetos/TinyG#196]
Hello , 

Just for information if you need to update this board, it's could be interesting to include some ferrite (ESD). Currently for some project we add some ESD equipment outside the board but I thing with few ferrite we can do the same and it's not so expensive (<5€ or if the customer don't want to pay , you can install one 0 ohm resistance ) 

For that you need to install 4 Ferrite (> 2.5A) for each motor and maybe one other (power) 

Example: http://uk.farnell.com/wurth-elektronik/742792515/ferrite-bead-0-05ohm-3a-1812/dp/1635779RL

If you want any information do not hesitate to send me a message. 
Best regards, 
Matthieu

**Comment by ril3y** [comment]
Thanks for the input.  We will take a look at the new g2core board. @aldenhart @mattpatt59
