### ISSUE TITLE
Uploading Firmware With Arduino IDE

### ISSUE THREAD

**Issue by cago6586** [synthetos/TinyG#200]
Hello,

I am having issues updating the firmware on my TinyG using the arduino IDE. I have uploaded firmware to the board like this before, but it is not working anymore. I am getting an error :

In file included from sketch\canonical_machine.c:101:0:

hardware.h:255: error: unknown type name 'PORT_t'

  PORT_t *st_port[MOTORS];  // bindings for stepper motor ports (stepper.c)

  ^

This is preventing me from uploading the firmware. Does anyone know how to work around this?

Thanks,
Carmelo

**Comment by ril3y** [comment]
To my knowledge this is not possible.  You can avr studio 7 to compile tinyg and then upload it with our uploader or use avr studio 7 and a atmel programmer directly.
https://github.com/synthetos/TinyG/wiki/TinyG-TG-Updater-App
