### ISSUE TITLE
Serial port JSON server connecttion fail

### ISSUE THREAD

**Issue by shczm** [synthetos/TinyG#203]
Hi,
I download the Serial port JSON server  and run it , It said:  
staring server and webscoket on 192.168.7.105:8989
the Serial port JSON server is now running

Then I put 192.168.7.105:8989 into the chilipeppr and clicked connect, after several seconds, it said:
Failed to connect to host.
Serial port ajax error

Could anyone help me?
Thanks a lot

**Comment by johnlauer** [comment]
Maybe a firewall blocking it? Are you running both on the same computer?

**Comment by shczm** [comment]
Thank you for your reply , Johnlauer.
I tried again after closed the firmware, the error remains,
I am not sure if I do it in a correct way:

1. download the serial-port-json-server.exe, the dubble click on it,
2. When the conmmand line window appears, find out the IP address and put it in the chilipeppr ,then click connect.

I use win10.

Thanks

**Comment by chilipeppr** [comment]
Yup. Did you figure it out? Are you running it on the same computer? Or separate computers like many folks do?

**Comment by shczm** [comment]
Hi John lauer,
I think the reason was that I used a Proxy server.
So I want to use stand alone chilipeppr. However, I followed the instructions of the "chilipeppr-offline" page, it did not work properly.

![chilipeppr](https://cloud.githubusercontent.com/assets/25112766/26182195/1febd952-3ba9-11e7-8c7e-7f76493372ef.JPG)

**Comment by chilipeppr** [comment]
You'd have to post to that chilipeppr-offline Github for help. Not sure how much they support it.

**Comment by shczm** [comment]
Hi John lauer,
Finally I got the online version of chilipeppr connected to the serial port JSON server.
However it seemed that it did not work: 
I could not jog, 
If I loaded load a G code file , It could not run it

![2017-05-19_7-58-22](https://cloud.githubusercontent.com/assets/25112766/26228219/73895f6e-3c6a-11e7-8e6f-0ca7193510bc.jpg)

Thanks

**Comment by chilipeppr** [comment]
Look at how your serial port says programming port. That's wrong

**Comment by DanalEstes** [comment]
Does it work online?  If it DOES work online, and DOES NOT work offline,
please open an issue on the ChilipepperOffiline repository.

**Comment by chilipeppr** [comment]
That has nothing to do with it. Your due isnt plugged into the correct port.

**Comment by shczm** [comment]
I downloaded the firware from here:
![33](https://cloud.githubusercontent.com/assets/25112766/26228855/a8be3dee-3c6f-11e7-80b5-2bb28e34bac6.JPG)
is that a right firmware?

**Comment by chilipeppr** [comment]
Move your USB cable to other port

**Comment by shczm** [comment]
the Serial port JSON server said:
![1111111111](https://cloud.githubusercontent.com/assets/25112766/26228952/838b9f8e-3c70-11e7-9d00-69c09b9ba0b9.JPG)
but the conmection is fail

![3333333](https://cloud.githubusercontent.com/assets/25112766/26229040/3399b2ee-3c71-11e7-80d5-5529c3d8e660.JPG)

**Comment by DanalEstes** [comment]
Sorry, John, I crossed this thread with another one from the other day.  As
you say, offline has nothing to do with this discussion.
