### ISSUE TITLE
Problems with Sending Codes to TinyG

### ISSUE THREAD

**Issue by routerboiz** [synthetos/TinyG#206]
Hi, I am a high school student in an Engineering class. My group and I are building a CNC Router out of a TinyG, 3 NEMA 23 Motors, and a spindle speed controller. We have got our motors running on jog mode through the Universal G-Code Sender, but we cannot figure out how to send codes to the TinyG through either the Universal G-Code Sender or through Coolterm. We have tried to send $100, $101, and $102 GRBL codes to edit the steps/mm, but we have never successfully sent the codes. We have also tried other codes to tune our motors, but neither our group nor our teacher can figure out what codes to send, or where to send them. If you have any ideas, please send them our way! Thanks.

**Comment by ril3y** [comment]
@routerboiz 

TinyG is not grbl :) 
https://github.com/synthetos/TinyG/wiki/TinyG-Configuration-for-Firmware-Version-0.97 

Read the wiki to figure out how to configure TinyG.
