### ISSUE TITLE
External Stepper Driver

### ISSUE THREAD

**Issue by 2gocnc** [synthetos/TinyG#207]
Hello everybody, 

I have a cnc with nema 23 steppers and i would drive them with 4,4A. 
So i bought some external stepper driver, but the external driver needs signals with minimal 5V and the Signals from the TinyG board have only 3,4V.

Can i change something on the TinyG to push the Signal?

Thanks for helping me,
Franz

**Comment by ril3y** [comment]
No.  Not on tinyg.  You could make a logic level converter board that would do the trick however.
