### ISSUE TITLE
Tinyg 3.3vt current draw total

### ISSUE THREAD

**Issue by CAReeser** [synthetos/TinyG#222]
I have four optical switches, each drawing 10ma on each 3.3vt output. Is the limit of 30ma a total amount or a per pin amount? Can't tell from the schematics as I can't calculate the total current draw of the rest of the items on the board.

**Comment by DanalEstes** [comment]
Best answer is to see the Atmel data sheet.

Extract:

Although each I/O port can sink more than the test conditions (20mA at VCC
= 5V, 10mA at VCC = 3V) under steady state conditions (non-transient), the
following must be observed:

ATmega640/1280/2560:
1.)The sum of all IOL, for ports J0-J7, A0-A7, G2 should not exceed 200mA.
2.)The sum of all IOL, for ports C0-C7, G0-G1, D0-D7, L0-L7 should not
exceed 200mA.
3.)The sum of all IOL, for ports G3-G4, B0-B7, H0-B7 should not exceed
200mA.
4.)The sum of all IOL, for ports E0-E7, G5 should not exceed 100mA.
5.)The sum of all IOL, for ports F0-F7, K0-K7 should not exceed 100mA
