### ISSUE TITLE
Turn off LEDs

### ISSUE THREAD

**Issue by CAReeser** [synthetos/TinyG#224]
Is there a command that will turn off or disable all LED's.  
Six TG's in a box emits a lot of light.

Thx
Cliff

**Comment by troisiemetype** [comment]
Hi,

Unfortunately for you, since leds are connected between AOUT1 on TI stepper drivers, the only way to shut the leds would be to cut the trace near the leds.
That's true leds give a "let's go party" feel when a job is running!  :D

**Comment by troisiemetype** [comment]
Hi,

Unfortunately for you, since leds are connected between AOUT1 on TI stepper drivers, the only way to shut the leds would be to cut the trace near the leds.
That's true leds give a "let's go party" feel when a job is running!

Have a look at the schematics, page 3 and 4 for more information.

**Comment by DanalEstes** [comment]
Black tape.

**Comment by CAReeser** [comment]
Yeah, I was thinking fingernail polish..
Thanks,
Cliff

Sent from Mail for Windows 10
