### ISSUE TITLE
TinyG Shapeoko Setup

### ISSUE THREAD

**Issue by zorlack** [synthetos/TinyG#227]
On the [Shapeoko setup page](https://github.com/synthetos/TinyG/wiki/TinyG-Shapeoko-Setup), the motor instructions list $1pm = 0 (0 leaves steppers on if anything moves).

As of FW 440.20 Power Management Mode 0 seems to indicate "Disabled"

Is the documentation out of date, or am I misunderstanding PM0

Thanks!

**Comment by cmcgrath5035** [comment]
The https://github.com/synthetos/TinyG/wiki/TinyG-Shapeoko-Setup page is out of date with respect to the $_pm parameter.
For $fb=440.20, follow https://github.com/synthetos/TinyG/wiki/Power-Management

**Comment by ril3y** [comment]
Fixed
