### ISSUE TITLE
BeRTOS exceptions

### ISSUE THREAD

**Issue by lpd-patrick** [synthetos/TinyG#228]
The following files do not contain the BeRTOS exception:
* config_app.c/h
* gcode_parser.c/h - Seems pretty hard to not use this file and without the exception would enforce the full GPLv2 on my work.
* help.c/h
* main.c
* plan_arc.c/h - The other plan_* files DO contain the exception. Why not this one?
* plan_line.h - However the .c file does, was this in error?
* system.c/h
* test.c/h
* tinyg.h - This file is included by every other .c file, whereby nullifying the exception.
* xio.c - However the .h file does, was this in error?

Please confirm that these file are all meant to NOT have the exception.

At the end of the day, I'm just trying to figure out what I can and can't do when integrating this into my proprietary device. It's not clear yet what we'd like to add, but most likely it would be specific to our integration and we'd want to protect that IP.

**Comment by aldenhart** [comment]
Please contact synthetos@gmail.com directly
