### ISSUE TITLE
Cannot put 'A' axis into G91 mode or get it completely out of rotary mode.

### ISSUE THREAD

**Issue by CAReeser** [synthetos/TinyG#231]
Z axis does as expected. 'A' axis is different. Even though it says standard axis mode = 1, some settings in 'A" are still in degrees and it will not operate in G91 incremental mode. All axis  are initialized with exactly the same init commands.

    init_cmds_list1 = ["$gun=1", "$1ma=0", "$2ma=1", "$3ma=2", "$4ma=3", 
                    '$xam=1', '$yam=1', '$zam=1', '$aam=1', 
                    "$1sa=1.8", "$2sa=1.8", "$3sa=1.8","$4sa=1.8",
                    "$1tr=2.0", "$2tr=2.0", "$3tr=2.0", "$4tr=2.0", 
                    "$1pm=3", "$2pm=3","$3pm=3", "$4pm=3",
                    '$xjm=5','$yjm=5','$zjm=5','$ajm=5' ] 
    init_cmds_list2 =  ['$xvm=600', '$yvm=600', '$zvm=600', '$avm=600', 
                    '$xfr=600',  '$yfr=600',  '$zfr=600',  '$afr=600', 
                    '$xtm=370', '$ytm=370', '$ztm=370', '$atm=370', 
                    '$xtn=0', '$ytn=0', '$ztn=0', '$atn=0', 
                    '$xSV=500', '$ySV=500', '$zSV=500', '$aSV=500']  
                      
    init_cmds_list3 = ['$ej=0', '$avm=600', '$tv=1', '$qv=0', '$sv=0','$gdi=1']  

From $$ screen capture:

[gun] default gcode units mode    1 [0=G20,1=G21]
[gco] default gcode coord system  1 [1-6 (G54-G59)]
[gpa] default gcode path control  2 [0=G61,1=G61.1,2=G64]
[gdi] default gcode distance mode 1 [0=G90,1=G91]

[zam] z axis mode                 1 [standard]
[zvm] z velocity maximum        600 mm/min
[zfr] z feedrate maximum        600 mm/min
[ztn] z travel minimum            0.000 mm
[ztm] z travel maximum          370.000 mm
[zjm] z jerk maximum              5 mm/min^3 * 1 million
[zjh] z jerk homing              40 mm/min^3 * 1 million
[zjd] z junction deviation        0.0500 mm (larger is faster)
[zsn] z switch min                0 [0=off,1=homing,2=limit,3=limit+homing]
[zsx] z switch max                1 [0=off,1=homing,2=limit,3=limit+homing]
[zsv] z search velocity         500 mm/min
[zlv] z latch velocity          100 mm/min
[zlb] z latch backoff             5.000 mm
[zzb] z zero backoff              1.000 mm

[aam] a axis mode                 1 [standard]
[avm] a velocity maximum        600 deg/min
[afr] a feedrate maximum        600 deg/min
[atn] a travel minimum            0.000 deg
[atm] a travel maximum          370.000 deg
[ajm] a jerk maximum              5 deg/min^3 * 1 million
[ajh] a jerk homing           11520 deg/min^3 * 1 million
[ajd] a junction deviation        0.0500 deg (larger is faster)
[ara] a radius value              0.1989 deg
[asn] a switch min                1 [0=off,1=homing,2=limit,3=limit+homing]
[asx] a switch max                0 [0=off,1=homing,2=limit,3=limit+homing]
[asv] a search velocity         500 deg/min
[alv] a latch velocity          100 deg/min
[alb] a latch backoff             5.000 deg
[azb] a zero backoff              2.000 deg

**Comment by cmcgrath5035** [comment]
I suggest you re-read the wiki section again https://github.com/synthetos/TinyG/wiki/TinyG-Configuration-for-Firmware-Version-0.97#axis-settings
Setting $AAM=1 puts the A axis in standard Rotational mode.
There is no way to put A,B or C into Linear mode.

You can, however, set $AAM=3, rotational mode, and get linear travel interpretation.
You would likely have to hand craft the Gcode, I have not seen a gCode  generator that will do it for you
