### ISSUE TITLE
Wiki page 'scripting' missing

### ISSUE THREAD

**Issue by myk3y** [synthetos/TinyG#234]
On page https://github.com/synthetos/TinyG/wiki/TinyG-Configuration-for-Firmware-Version-0.97

It has a link: "Note: If you are scripting or otherwise automating settings see Scripting Settings"

The http link 'Scripting Settings' is invalid.

I would like to save my settings via JSON and script reloading them.

The Googler doesn't return anything useful for 'tinyg scripting'

**Comment by ril3y** [comment]
fixed

**Comment by myk3y** [comment]
> fixed

That’s impressive - only (checks notes) 2 years, 7 months, 17 days to make a documentation change.

Golf Clap

**Comment by ril3y** [comment]
Yah we have moved pretty much onto G2core completely.  Sorry for the delay :)
