### ISSUE TITLE
TinyG will not connect to Mojave 10.14.6

### ISSUE THREAD

**Issue by MonkeyManGuy** [synthetos/TinyG#251]
Using a macbook with Thunderbolt 3 Ports my TinyG will not connect. It doesnt appear in system report > hardware > usb and coolterm cannot see it in the terminal connection.

I tried the 2.4.2 VCP Driver and then next installed the older 2.2.18 Driver. Both of which now show up in system report > software > extensions

Ive seen a few discussions of this problem scattered across the internet. I ended up resetting the SMC to no avail. This TinyG has been used before on an older macbook air and does function.

Please advise as I need help :)

**Comment by ril3y** [comment]
I have seen this before and have had to use a USB hub to get this to work.
