### ISSUE TITLE
No mounting holes for cooling the drivers

### ISSUE THREAD

**Issue by cdwijs** [synthetos/TinyG#256]
Hi All,

We are using a Tiny G v8. We noticed the drivers getting warm, so we wanted to mount a strip of aluminum at the bottom side of the board, and then connect this strip of aluminum to the bottom of an aluminum case.

Problem is, we only have the 4 mounting holes at the corners of the board, so we can't press the aluminum strip firmly to the board. It would be nice if there were 2-4 holes in the board surrounding each driver.

Cheers,
Cedric

**Comment by ril3y** [comment]
The tinyg v8 hardware is in its final form.  I would suggest that you use active cooling like a fan as we have seen this works pretty good.
