### ISSUE TITLE
X-axis homing issue (all others OK)

### ISSUE THREAD

**Issue by scott14468** [synthetos/TinyG#279]
Hi Riley & Rob,

We are having another issue getting an axis setup.  This is another axis on a rotary stage that has two optical slot sensors about 5 degrees apart for a total travel of 355 degrees or so.  One is to act as home/min/limit the other as the max limit.  The signals look good, < 300 mV low and 3.3V high.  We’re using aluminum anodized flags and HOA1877 slot sensors.  The device’s other two axis use micro-switches for min/home and max limits.  All switches are normally closed and open on limit.  I’ve watched the limit signals with an oscilloscope when the motor moves, and they look OK, good levels and monotonic rise/fall times.

I’ve attached settings.

The Y and Z axis work as expected, X has the problem.  When we home, X proceeds toward home then stops with the Xmin signal high (as expected), but reports a large negative position, -359 and $home reports the axis is not homed.  We’ve tried lots of settings for XLB and XZB without any success.

Any thoughts much appreciated!

Best,
Scott

[y.txt](https://github.com/synthetos/TinyG/files/11080903/y.txt)

**Comment by scott14468** [comment]
Never mind!  We've resolved the issue.  We have ST set backward because it was compensating for too low of a jerk value on three other axis.  With the jerk value increased and polarity corrected, all axis are working properly.

Scott

**Comment by ril3y** [comment]
Glad you got it!  I just saw this.
