### ISSUE TITLE
License is unclear

### ISSUE THREAD

**Issue by krasin** [synthetos/TinyG#42]
Hi TinyG team,

there's no LICENSE / COPYING file on the top of the repository (and it does not seem to be anywhere else as well). This makes it harder to make a bet and use TinyG, since different licenses impose very different set of restrictions.

Could you please add a LICENSE to your code?

**Comment by lpd-patrick** [comment]
Now the firmware/LICENSE.txt file notes a GPLv2. So which is accurate? v2 or v3?

**Comment by aldenhart** [comment]
It's now v2 with the BeRTOS exceptions for use of some files. Please see here. 
https://github.com/synthetos/TinyG/wiki/TinyG-Licensing

If there is ambiguity in any of the files or other project artifacts pelase let us know.
