### ISSUE TITLE
invalid JSON response

### ISSUE THREAD

**Issue by belisarius222** [synthetos/TinyG#55]
I've tried this a couple times now and always get the same response, so I thought I'd share the reproduction.  

sent: `{"jv":5}`
received: `{"r":{"jv":5,"f":[1,0,9,8847]}}`
sent: `{"sr":{"line":true,"posx":true,"posy":true,"posz":true,"posa":true,"feed":true,"coor":true,"dist":true,"frmo":true,"momo":true,"plan":true,"path":true,"gc":true,"vel":true,"unit":true,"stat":true}}`

received: 

```
{"r":{"sr":{"line":0,"posx":0.000,"posy":0.000,"posz":0.000,"posa":0.000,"feed":0.00,"coor":1,"dist":0,"frmo":0,"momo":0,"plan":0,"path":2,"gc":"{"sr","vel":0.00,"unit":1,"stat":1},"f":[1,0,198,8293]}}
```

This last line received is not valid JSON.  The value for its "gc" key starts with an open quote, but does not end the string.  I also feel like the value of the "gc" is supposed to be an object, not a string, in which case the "sr" key should have some sort of value associated with it.

Any ideas for workarounds / bug fixes?

Thanks!

**Comment by Taxi4110** [comment]
I just wanted to note, that this bug still exists in firmware 440.14!
