### ISSUE TITLE
IC heating on disabled/unconnected motors

### ISSUE THREAD

**Issue by mcgyvr** [synthetos/TinyG#89]
Just wanted to point this out as IMO as I didn't expect this

If you have... for example.. nothing attached to one of the motors outputs on the tinyg board and have even set that motor output to a disabled axis the motor LED still stays on and the IC is "self-heating" itself. 
"IF" I go back and turn it to "low power idle" mode then the light does turn off/heating is reduced BUT my question/issue is why is it even on it the first place when I have that axis disabled. 

I would expect a "disabled" axis/motor to be well... disabled..dead..off.

**Comment by aldenhart** [comment]
This issue is addressed in edge build 440.13 (or later)
