### ISSUE TITLE
G2 Command with Large Y-Offset Results in Crash

### ISSUE THREAD

**Issue by NathanBerge** [synthetos/TinyG#95]
Running the following lines of g-code results in a crash where my laser cutter continues to drift in one direction until it goes out of bounds:

G1 X  44.571 Y 132.120
G2 X  44.603 Y 132.115 I-536.932 J-3460.792

I fixed the problem by rewriting the commands as:

G1 X  44.571 Y 132.120
G1 X  44.603 Y 132.115

The g-code I'm using has thousands of lines of code that run without error, generated by https://code.google.com/p/dxf2gcode/

**Comment by aldenhart** [comment]
Fixed in edge build 440.13
