### ISSUE TITLE
G38.2 not working with NC limit switches

### ISSUE THREAD

**Issue by jonhart** [synthetos/TinyG#99]
In the latest build, with NC limit switches, running the G38.2 command doesn't initiate any motion at all. Note that my touch plate is wired to A min as an NO homing only switch.

**Comment by melristau** [comment]
"Zmin pin must be wired NO."
How do you WIRE the Zmin pin to be NO?
Helpful to know.

**Comment by mikest** [comment]
use a N.O. switch instead of an N.C. switch. For some switches (SPDT), they can be wired in either configuration.

--mikest

**Comment by ril3y** [comment]
To elaborate.  Look at this image.

http://jv.wikipedia.org/wiki/Gambar:Spdt_limit_switch.jpg

You can see 3 pins.  One is labeled NO and the other NC.  This is what Mike
is talking about.

Riley

**Comment by melristau** [comment]
Thanks Riley - I get it now...
In the context of notes on probing w/ g38.2, it makes sense that the alligator clip & plate technique would be a NO circuit.  "Zmin pin must be wired NO", makes sense if referring to a three-pole switch. But this process requires a two-pole probe. So, I was thinking  Andrew knew of some way to connect at the board end that would override the [st] switch type command!
Me being inexperienced with CNC and way too literal!
Regardless, that thread helped me get my Z working as it should.
Best to you,

Mel Ristau
Ristau Sculpture, LLC
8001 Country Farms Ct.
Fort Collins, CO. 80528
Mountain Standard Time
970 377-3713

On Jan 29, 2015, at 8:06 PM, ril3y <notifications@github.com> wrote:

To elaborate. Look at this image.

http://jv.wikipedia.org/wiki/Gambar:Spdt_limit_switch.jpg

You can see 3 pins. One is labeled NO and the other NC. This is what Mike
is talking about.

Riley

**Comment by ril3y** [comment]
Very good!

Thanks for the feed back.

Riley
